export const CITY_DATA = [
	{ "city": "Kolkata", "state": "West Bengal" },
	{ "city": "Siliguri", "state": "West Bengal" },
	{ "city": "Durgapur", "state": "West Bengal" },
	{ "city": "Asansol", "state": "West Bengal" },
	{ "city": "Howrah", "state": "West Bengal" },
	{ "city": "Bhubaneswar", "state": "Odisha" },
	{ "city": "Cuttack", "state": "Odisha" },
	{ "city": "Rourkela", "state": "Odisha" },
	{ "city": "Sambalpur", "state": "Odisha" },
	{ "city": "Brahmapur", "state": "Odisha" },
	{ "city": "Puri", "state": "Odisha" },
	{ "city": "Balasore", "state": "Odisha" },
	{ "city": "Baripada", "state": "Odisha" },
	{ "city": "Jeypore", "state": "Odisha" },
	{ "city": "Bhadrak", "state": "Odisha" },
	{ "city": "Jharsuguda", "state": "Odisha" },
	{ "city": "Angul", "state": "Odisha" },
	{ "city": "Paradip", "state": "Odisha" },
	{ "city": "Dhenkanal", "state": "Odisha" },
	{ "city": "Rayagada", "state": "Odisha" },
	{ "city": "Koraput", "state": "Odisha" },
	{ "city": "Kendujhar", "state": "Odisha" },
	{ "city": "Sundargarh", "state": "Odisha" },
	{ "city": "Nabarangpur", "state": "Odisha" },
	{ "city": "Malkangiri", "state": "Odisha" },
	{ "city": "Jagatsinghpur", "state": "Odisha" },
	{ "city": "Kalahandi", "state": "Odisha" },
	{ "city": "Subarnapur", "state": "Odisha" },
	{ "city": "Phulbani", "state": "Odisha" },
	{ "city": "Bargarh", "state": "Odisha" },
	{ "city": "Nuapada", "state": "Odisha" },
	{ "city": "Ganjam", "state": "Odisha" },
	{ "city": "Nayagarh", "state": "Odisha" },
	{ "city": "Kendrapara", "state": "Odisha" },
	{ "city": "Balangir", "state": "Odisha" },
	{ "city": "Mumbai", "state": "Maharashtra" },
	{ "city": "Pune", "state": "Maharashtra" },
	{ "city": "Nagpur", "state": "Maharashtra" },
	{ "city": "Thane", "state": "Maharashtra" },
	{ "city": "Nashik", "state": "Maharashtra" },
	{ "city": "Bangalore", "state": "Karnataka" },
	{ "city": "Mysore", "state": "Karnataka" },
	{ "city": "Hubli", "state": "Karnataka" },
	{ "city": "Mangalore", "state": "Karnataka" },
	{ "city": "Belgaum", "state": "Karnataka" },
	{ "city": "Delhi", "state": "Delhi" },
	{ "city": "New Delhi", "state": "Delhi" },
	{ "city": "Dwarka", "state": "Delhi" },
	{ "city": "Rohini", "state": "Delhi" },
	{ "city": "Saket", "state": "Delhi" },
	{ "city": "Chennai", "state": "Tamil Nadu" },
	{ "city": "Coimbatore", "state": "Tamil Nadu" },
	{ "city": "Madurai", "state": "Tamil Nadu" },
	{ "city": "Salem", "state": "Tamil Nadu" },
	{ "city": "Tirunelveli", "state": "Tamil Nadu" },
	{ "city": "Hyderabad", "state": "Telangana" },
	{ "city": "Warangal", "state": "Telangana" },
	{ "city": "Nizamabad", "state": "Telangana" },
	{ "city": "Karimnagar", "state": "Telangana" },
	{ "city": "Khammam", "state": "Telangana" },
	{ "city": "Ahmedabad", "state": "Gujarat" },
	{ "city": "Surat", "state": "Gujarat" },
	{ "city": "Vadodara", "state": "Gujarat" },
	{ "city": "Rajkot", "state": "Gujarat" },
	{ "city": "Gandhinagar", "state": "Gujarat" },
	{ "city": "Jaipur", "state": "Rajasthan" },
	{ "city": "Jodhpur", "state": "Rajasthan" },
	{ "city": "Udaipur", "state": "Rajasthan" },
	{ "city": "Bikaner", "state": "Rajasthan" },
	{ "city": "Ajmer", "state": "Rajasthan" },
	{ "city": "Amritsar", "state": "Punjab" },
    { "city": "Ludhiana", "state": "Punjab" },
    { "city": "Jalandhar", "state": "Punjab" },
    { "city": "Patiala", "state": "Punjab" },
    { "city": "Bathinda", "state": "Punjab" },
    
    { "city": "Lucknow", "state": "Uttar Pradesh" },
    { "city": "Kanpur", "state": "Uttar Pradesh" },
    { "city": "Varanasi", "state": "Uttar Pradesh" },
    { "city": "Agra", "state": "Uttar Pradesh" },
    { "city": "Meerut", "state": "Uttar Pradesh" },

    { "city": "Bhopal", "state": "Madhya Pradesh" },
    { "city": "Indore", "state": "Madhya Pradesh" },
    { "city": "Gwalior", "state": "Madhya Pradesh" },
    { "city": "Jabalpur", "state": "Madhya Pradesh" },
    { "city": "Ujjain", "state": "Madhya Pradesh" },

    { "city": "Guwahati", "state": "Assam" },
    { "city": "Dibrugarh", "state": "Assam" },
    { "city": "Silchar", "state": "Assam" },
    { "city": "Jorhat", "state": "Assam" },
    { "city": "Tinsukia", "state": "Assam" },

    { "city": "Shimla", "state": "Himachal Pradesh" },
    { "city": "Manali", "state": "Himachal Pradesh" },
    { "city": "Dharamshala", "state": "Himachal Pradesh" },
    { "city": "Solan", "state": "Himachal Pradesh" },
    { "city": "Kullu", "state": "Himachal Pradesh" },

    { "city": "Gangtok", "state": "Sikkim" },
    { "city": "Namchi", "state": "Sikkim" },
    { "city": "Gyalshing", "state": "Sikkim" },
    { "city": "Mangan", "state": "Sikkim" },
    { "city": "Jorethang", "state": "Sikkim" },

    { "city": "Imphal", "state": "Manipur" },
    { "city": "Thoubal", "state": "Manipur" },
    { "city": "Churachandpur", "state": "Manipur" },
    { "city": "Bishnupur", "state": "Manipur" },
    { "city": "Kakching", "state": "Manipur" },

    { "city": "Aizawl", "state": "Mizoram" },
    { "city": "Lunglei", "state": "Mizoram" },
    { "city": "Serchhip", "state": "Mizoram" },
    { "city": "Champhai", "state": "Mizoram" },
    { "city": "Saiha", "state": "Mizoram" },

    { "city": "Itanagar", "state": "Arunachal Pradesh" },
    { "city": "Pasighat", "state": "Arunachal Pradesh" },
    { "city": "Ziro", "state": "Arunachal Pradesh" },
    { "city": "Tawang", "state": "Arunachal Pradesh" },
    { "city": "Tezu", "state": "Arunachal Pradesh" },

    { "city": "Kohima", "state": "Nagaland" },
    { "city": "Dimapur", "state": "Nagaland" },
    { "city": "Mokokchung", "state": "Nagaland" },
    { "city": "Tuensang", "state": "Nagaland" },
    { "city": "Wokha", "state": "Nagaland" },

    { "city": "Shillong", "state": "Meghalaya" },
    { "city": "Tura", "state": "Meghalaya" },
    { "city": "Nongpoh", "state": "Meghalaya" },
    { "city": "Jowai", "state": "Meghalaya" },
    { "city": "Baghmara", "state": "Meghalaya" },

    { "city": "Ranchi", "state": "Jharkhand" },
    { "city": "Jamshedpur", "state": "Jharkhand" },
    { "city": "Dhanbad", "state": "Jharkhand" },
    { "city": "Bokaro", "state": "Jharkhand" },
    { "city": "Hazaribagh", "state": "Jharkhand" },

    { "city": "Raipur", "state": "Chhattisgarh" },
    { "city": "Bhilai", "state": "Chhattisgarh" },
    { "city": "Bilaspur", "state": "Chhattisgarh" },
    { "city": "Korba", "state": "Chhattisgarh" },
    { "city": "Durg", "state": "Chhattisgarh" },

    { "city": "Pondicherry", "state": "Puducherry" },
    { "city": "Karaikal", "state": "Puducherry" },
    { "city": "Mahe", "state": "Puducherry" },
    { "city": "Yanam", "state": "Puducherry" },

    { "city": "Port Blair", "state": "Andaman and Nicobar Islands" },
    { "city": "Car Nicobar", "state": "Andaman and Nicobar Islands" },
    { "city": "Hut Bay", "state": "Andaman and Nicobar Islands" },
    { "city": "Diglipur", "state": "Andaman and Nicobar Islands" },
    { "city": "Mayabunder", "state": "Andaman and Nicobar Islands" },

    { "city": "Daman", "state": "Daman and Diu" },
    { "city": "Diu", "state": "Daman and Diu" },

    { "city": "Silvassa", "state": "Dadra and Nagar Haveli" },

    { "city": "Leh", "state": "Ladakh" },
    { "city": "Kargil", "state": "Ladakh" }
];
